import 'package:flutter/material.dart';
const bgColor = Color(0xFFF9FAFB);
const cardColor = Colors.greenAccent;
const easyColor = Color(0xFFE8F5E9);
const mediumColor = Color(0xFFFFF8E1);
const hardColor = Color(0xFFFDECEA);
const easyText = Color(0xFF2E7D32);
const mediumText = Color(0xFFF9A825);
const hardText = Color(0xFFC62828);
const primaryBlue = Color(0xFF1E88E5);